### ISSUE TITLE
Super minor typo during import

### ISSUE THREAD

**Issue by p1839251** [Alone2/studyFlash#9]
https://github.com/Alone2/studyFlash/blob/0510a754c08e9f6dd78eba9b6cc5a23156af64ac/studyFlash/csv_handler.py#L15

alredy - already

**Comment by Alone2** [comment]
Thank you for submitting this issue.
I'll fix it. It will maybe take some time, as I have a lot to do as of late.

Push request for error like these are always welcome :)

It is a mess with all this output stuff inside the source code. 
I really need to implement internationalization, so that the output is centralized and can be translated.
